### PR TITLE
#8 done

### PR DESCRIPTION
**Pull request by k-deepak04**
added the social media link and updated  the design of footer with good hover buttons.

### CODE REVIEW

**Comment by k-deepak04** [comment]
Previous design.
Screenshot (197)

new design.
the social-icons will remain grey and on hover will get the color
Screenshot 2023-04-18 112356
Screenshot 2023-04-18 112406

**Comment by gbowne1** [comment]
Thanks @k-deepak04 for fixing this. I'm pretty sure I can now make this the way I want it with the work you did.

**Comment by k-deepak04** [comment]
@gbowne1 always ready to help.
you can just open the issue and i'll help you in making it the way you want :)

**Comment by gbowne1** [comment]
Thanks so much for all of your help.  @k-deepak04   I will definitely.  This site is a replacement for https://github.com/gbowne1/personalsite and that repo will go away once this is complete.

:)

**Comment by k-deepak04** [comment]
okay
Do you have any design idea or reference site that we can follow while building this thing.

**Comment by gbowne1** [comment]
I have pics of the personalsite repo rendering that I linked to above here, that I can share.  but that too is a complete mess.  I was experimenting with some ideas.

**Comment by k-deepak04** [comment]
Add those pics in the discussion tab. I'll get a reference and then I'll redesign it accordingly.
Also give me the contents you want to add in the footer

**Comment by gbowne1** [comment]
@k-deepak04 

Footer
  - I have links for:
    YouTube, Instagram, Facebook, Reddit, Github, Twitter
 - (C) Gregory Bowne 2023
 
The TopNav needs to be 1884x60px in my view, but I added a breakpoint specification just now for any media queries

There are favicons (and other images) in /src/assets/images/  I would prefer a .ico file instead of a PNG.  Use one for the browser tab icon and the other is a logo for the topnav / topbar (the 50px one).

I thought about using a background with either my nightseattle.jpg or seattle.jpg.  These two I took myself.

Make some appropriate use of hello-my-name-is-greg.jpg as well.  on whatever route loads at "/" It could be made smaller.  It's a very big image.

The topnav should be blue or black.  My thoughts were #4169e or #2c3e5

The topnav/topbar should have button or icon links to Home, About, Gallery, Blog, Contact  and a Login icon on the far right.

Gallery is just a page where i can show off pictures of my projects.

**Comment by gbowne1** [comment]
Footer @ roughly 300px

Screenshot 2023-04-18 at 00-18-09 Bootstrap Example

**Comment by gbowne1** [comment]
The Contact page..

Screenshot 2023-04-18 at 00-23-34 Gregory Bowne

This form is way too huge..

**Comment by gbowne1** [comment]
This needs to be updated.  This could be either the Blog or About.  Either way I wanna do my writing there.
I would use cards or small containers.

Screenshot 2023-04-18 at 00-25-38 Gregory Bowne

**Comment by gbowne1** [comment]
If I also choose to do  a portfolio, I will include all my apps on here.. but..

Screenshot 2023-04-18 at 00-32-31 Portfolio Greg Bowne

**Pull request merged**
