### PR TITLE
#23 done

### PR DESCRIPTION
**Pull request by k-deepak04**
basic gallery page is designed with dummy images and text.

image

### CODE REVIEW

**Comment by k-deepak04** [comment]
@gbowne1 accept my current changes for the conflicts

**Comment by k-deepak04** [comment]
for now i have created this basic design .Further we will improve this one

**Review by gbowne1 — APPROVED** [review]
This change looks good.  It will need some work but this is good.

**Comment by gbowne1** [comment]
This has conflicts. Unable to merge.

**Review by gbowne1 — COMMENTED** [review]
Looks like this may have fixed it.

**Pull request merged**
